env: Pendulum-v0                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 100
nbTest: 1
freqVerbose: 100
freqOptim: 1000                                                                    # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 10000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 300
exploMode: 0                                                                          # Mode d'exploration. 0 = epsilon-greedy (les autres a regarder je sais plus)
explo: 0.1                                                                            # coefficient d'exploration initial
decay: 0.99999                                                                         # a la fin de chaque trajectoire, le coefficient d'explo est multiplié par ce facteur
gamma: 0.99                                                                          # Facteur de discount
p_learningRate: 0.00005
q_learningRate: 0.0005
rho: 0.995