env: Pendulum-v1                                                                      # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 100
nbTest: 1
freqVerbose: 100
freqOptim: 1000                                                                       # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 10000
maxLengthTest: 200                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 200